### ISSUE TITLE
CanICA bug standarize not found

### ISSUE THREAD

**Issue by grjd** [GaelVaroquaux/canica#2]
Hi,
CanICA returns an error if standarize is passed as an argument, otherwise it works.

canica = CanICA(n_components=20,standarize=preproc_parameters['standarize'],smoothing_fwhm=preproc_parameters['smoothing_fwhm'], detrend=preproc_parameters['detrend'],low_pass=preproc_parameters['low_pass'], high_pass=preproc_parameters['high_pass'],t_r=preproc_parameters['t_r'],memory="nilearn_cache", memory_level=2, threshold=3., verbose=10, random_state=0)
*** TypeError: __init__() got an unexpected keyword argument 'standarize'

**Comment by GaelVaroquaux** [comment]
This code is deprecated since a very long time. You should be using
nilearn:
http://nilearn.github.io/modules/generated/nilearn.decomposition.CanICA.html

**Comment by grjd** [comment]
I am using nilearn. 

from nilearn.decomposition import CanICA

canica = CanICA(n_components=20,
                    standarize=preproc_parameters['standarize'], ....

**Comment by GaelVaroquaux** [comment]
> I am using nilearn.

Then this is the wrong repository. See https://github.com/nilearn/nilearn
